# ---------------------------------------- #
# This is the config file of CraftEnhance. #
# ---------------------------------------- #

enable-debug: false
enable_crafting-debug: false
enable-recipes: true

# This update checker checks for new versions on the github page.
enable-updatechecker: true

# If this option is enabled, people can only see recipes that they have permissions to.
only-show-available: true

# Enable this to make the players learn the recipes (making them show up in the green recipe book)
learn-recipes: false

debug-prefix: "[DEBUG] "
global-prefix: "&7[&bCraft&dEnhance&7] &r"

#If it shall save the recipe when close menu
save_on_close: false

# Item providers is a different type of item comparison, it uses NBT paths to check if two items are equals
# to allow compatibility with custom item plugins.
# Instead of item matchers, the item provider override any comparison if it's applicable, otherwise will
# use the current recipe matcher.
item-provider:
  # Provider key with the comparable path(s)
  oraxen: 'PublicBukkitValues.oraxen:id'
  itemsadder:
    - 'itemsadder.namespace'
    - 'itemsadder.id'
  mmoitems:
    - 'MMOITEMS_ITEM_ID'
    - 'MMOITEMS_ITEM_TYPE'

# These permissions are used globally by all features of the plugin.
perms:
  recipe-editor: "craftenhance.edit"
  recipe-viewer: "craftenhance.view"
  item-editor: "craftenhance.edititems"
  categorys-editor: "craftenhance.edit_categorys"

messages:
  global:
    no-perms: "You don't have permission to do that."
  commands:
    show-options: "You entered an unfinished command. It can be completed by adding one of the following arguments: &e[PLACEHOLDER]&r."
    few-arguments: "Expected [PLACEHOLDER] arguments for the command." 
    only-for-players: "This command is only for players."